language: ruby
env:
  - RAILS_VERSION=3.2.22
  - RAILS_VERSION=4.2.5
  - RAILS_VERSION=5.0.0.beta1
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
matrix:
  exclude:
    - rvm: 2.1.8
      env: RAILS_VERSION=5.0.0.beta1
before_install: gem install bundler -v 1.11.2
